# Generated by Django 3.2.9 on 2021-11-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211111_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='eee', max_length=15),
            preserve_default=False,
        ),
    ]
