# Generated by Django 3.0.2 on 2021-06-18 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500, null=True)),
                ('username', models.CharField(max_length=500, null=True)),
                ('password', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=500)),
                ('image_link', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500, null=True)),
                ('has_sizes', models.CharField(max_length=500, null=True)),
                ('rating', models.IntegerField(null=True)),
                ('sku', models.CharField(max_length=500, null=True)),
                ('price', models.FloatField(null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.Customer')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
